spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.101/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true


server:
  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: D:\ideaProd\springBoot\sell_log\sell.log
#  level:
#    com.imooc.sell.LoggerTest : debug
